### ISSUE TITLE
Failed to apply plugin [id 'devicefarm'] The android or android-library has not been applied yet

### ISSUE THREAD

**Issue by twilly86** [awslabs/aws-device-farm-gradle-plugin#10]
I'm getting the following error when trying to setup the device farm gradle plugin.

Failed to apply plugin [id 'devicefarm'] The android or android-library has not been applied yet

Here is an example project where this is failing.

https://github.com/twilly86/AWSDeviceFarmTest

Could you see what I'm doing wrong?

The instructions aren't saying anything about needing the android plugin to get this to work.

**Comment by aniket-21** [comment]
Facing the same issue. Did u get any resolution for this?

**Comment by shivshankark** [comment]
@twilly86 / @aniket-21 , Not sure if you got this old issue resolved. You have to add the content under *[Configure your plugin..](https://github.com/awslabs/aws-device-farm-gradle-plugin/blob/master/README.md)* section to ***module specific*** build.gradle file. You would run into this error if the content is added in project's build.gradle file. 

The *buildscript* goes in project's build.gradle while the *plugin configuration* goes in module's build.gradle.

Hope this helps!!

**Comment by bradley-curran** [comment]
I've reworded the README.md to hopefully make this easier to understand. Closing.

**Comment by RWillemsen291180** [comment]
Still facing the problem. buildscript is in main project's build.gradle and devicefarm plugin is in module's build.gradle. Is there any install needed between?

**Comment by yavgel** [comment]
having the same problem
