### ISSUE TITLE
How to Package the Test Content

### ISSUE THREAD

**Issue by Code1942** [awslabs/aws-device-farm-gradle-plugin#12]
Like explained in the below article we can use the command "mvn clean package -DskipTests=true"
to package the test content that will be uploaded. Similarly how can we package the test content for a gradle based project.

https://github.com/awslabs/aws-device-farm-appium-tests-for-sample-app

**Comment by bradley-curran** [comment]
Generating a new project in Android Studio will provide you with a great default setup for test packaging. 

There's some great info on the Android Developers website on testing. Here's some links that discuss it in more depth: 

- https://developer.android.com/studio/test/index.html
- https://developer.android.com/training/testing/index.html
- https://developer.android.com/training/testing/fundamentals.html
- https://developer.android.com/training/testing/unit-testing/index.html
