### ISSUE TITLE
How to specify build variant/apk file?

### ISSUE THREAD

**Issue by lewisob** [awslabs/aws-device-farm-gradle-plugin#13]
When running "gradle devicefarmUpload" my tests run using a debug version of the app.
I need to run against a release version of the app.

How can I specify a different version of the app to upload?

**Comment by andreschab90** [comment]
you just have to define your buildVariants in your build.gradle

**Comment by andreschab90** [comment]
@lewisob just define the test build type in the build.gradle

**Comment by lewisob** [comment]
Thanks.
