### ISSUE TITLE
Running the plugin says tests were skipped

### ISSUE THREAD

**Issue by shivani4** [awslabs/aws-device-farm-gradle-plugin#19]
The build is successful and I get a link to devicefarm and the test run. However, all the tests are skipped. Please can you advise the options available?

```gradle
apply plugin: 'devicefarm'

devicefarm {

    projectName "*******" // required: Must already exists.

    devicePool "*********" // optional: Defaults to "Top Devices"

    //useUnmeteredDevices() // optional if you wish to use your un-metered devices


    authentication {
        accessKey "******"
        secretKey "*****"
    }

    // optional block, radios default to 'on' state, all parameters optional
    devicestate {
        wifi "on"
        bluetooth "off"
        gps "off"
        nfc "on"
        latitude 47.6204 // default
        longitude -122.3491 // default
    }
    instrumentation {
        
    }
}
```

**Comment by shivani4** [comment]
Please can I have a reply on the above issue as I am still facing it.

**Comment by andreas-marschke** [comment]
That's unfortunately something you'll have to take up with AWS and the ADF Support in their Forum.

**Comment by bradley-curran** [comment]
I've seen this before in my own runs when the configuration has `useUnmeteredDevices()` set. 

If you don't have private devices this will cause all your tests to be skipped. 

I've reworked the README to hopefully make this clearer. If this issue continues to come up I'll reevaluate how we handle this feature. Please reopen this issue if you're still having problems.
