### ISSUE TITLE
AWS Device Farm configuration is NOT VALID (with valid config)

### ISSUE THREAD

**Issue by fabiendevos** [awslabs/aws-device-farm-gradle-plugin#4]
I get this message:

    AWS Device Farm configuration is NOT VALID
    AWS Device Farm configuration is NOT VALID

(the message appears twice) for the config below (the projectName, accessKey and secretKey are working, I can use them to send tests through the command line):

    devicefarm {
    
      projectName "My Android App"
    
      authentication {
        accessKey "XXXXXXXXXXXXXXXX"
        secretKey "YYYYYYYYYYYYYYYYYYYY"
      }
    
    }

The devicefarmUpload task is therefore skipped (I'm guessing because the config is considered not valid).

**Comment by MisumiRize** [comment]
This problem is fixed by #2, but fixed plugin is not seem to be published yet.

**Comment by fabiendevos** [comment]
Thanks, any idea when it will be published?

**Comment by MisumiRize** [comment]
Sorry, I don't know when the change will be published.
But you can distribute the newest one by using Bintray.

**Comment by fabiendevos** [comment]
@r7o is there any chance you could release it? This is a pretty blocking issue. :)

**Comment by EugeneDeveloper** [comment]
I am also interesting about that issue. It blocked. Is it possible to send test using command line?
I also every time have problem with using deviceState property:
```
Error:(86, 0) No such property: on for class: com.amazonaws.devicefarm.extension.DeviceState
```

**Comment by thesimran** [comment]
I'm having the same issue. Any update on a release date?

**Comment by trentpeterson** [comment]
Hi all, we're working on this now and should have a new build shortly. Thanks for your patience!

**Comment by michael-b-willingham** [comment]
We released the latest changes from github as version 1.1: 'com.amazonaws:aws-devicefarm-gradle-plugin:1.1'

**Comment by fabiendevos** [comment]
Thanks a lot!

**Comment by michael-b-willingham** [comment]
I forgot to mention that anybody who was running into 
```
No such property: on for class: com.amazonaws.devicefarm.extension.DeviceState
``` 
should now surround their "on" or "off" with quotes in their device state enclosure. 

Here's an example: 

```
        // optional block, radios default to 'on' state, all parameters optional
        devicestate {

            extraDataZipFile file("relative/path/to/zip") // default null
            auxiliaryApps [file("path1"), file("path2")] // default empty list
            wifi "on"
            bluetooth "off"
            gps "off"
            nfc "on"
            latitude 47.6204 // default
            longitude -122.3491 // default
        }
```
